"""S8 Renderer: ``Briefing`` -> HTML -> PDF.

WeasyPrint is the primary engine because it supports the paged-media features
AGENTS.md §8 requires: running page numbers and a table of contents whose
entries carry page numbers (``target-counter``). Chromium cannot do the latter,
so it is only the fallback, and using it sets ``fallback = True`` on the result
so the manifest can never hide the switch.

macOS note (docs/decisions/001-runtime-and-renderer.md): WeasyPrint reaches
Homebrew's Pango through dyld, so ``DYLD_FALLBACK_LIBRARY_PATH`` has to be set
*before* ``weasyprint`` is imported. That is why the import happens inside a
function rather than at module scope.
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
import sys
from collections.abc import Sequence
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Protocol

from jinja2 import Environment, FileSystemLoader, select_autoescape
from pypdf import PdfReader

from briefing.errors import RenderError
from briefing.evidence import contains_cjk
from briefing.report.figures import OverviewEntry, render_topic_overview, truncate
from briefing.report.markdown import render_markdown
from briefing.report.references import (
    build_reference_map,
    build_references,
    format_authors,
    resolve_citations,
    resolve_claim_keys,
)
from briefing.schemas import Briefing, Claim, SearchPlan, SelectedPapers

logger = logging.getLogger(__name__)

PACKAGE_DIR = Path(__file__).resolve().parent
TEMPLATE_DIR = PACKAGE_DIR / "templates"
STYLESHEET = PACKAGE_DIR / "styles.css"
TEMPLATE_NAME = "report.html.jinja"

STAGE_HTML_PATH = "08_report.html"

# Homebrew's prefix on Apple silicon; the decision record pins this path.
HOMEBREW_LIB = "/opt/homebrew/lib"

CHROME_CANDIDATES = (
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Chromium.app/Contents/MacOS/Chromium",
    "/usr/bin/chromium",
    "/usr/bin/chromium-browser",
    "/usr/bin/google-chrome",
)

LABELS: dict[str, dict[str, str]] = {
    "en": {
        "title_suffix": "Literature Briefing",
        "subtitle": "Generated by an automated multi-agent pipeline",
        "toc": "Contents",
        "summary": "Executive summary",
        "overview": "Topic overview",
        "overview_caption": (
            "The papers this briefing is built on, and how each relates to the topic."
        ),
        "overview_table": "At a glance",
        "background": "Background",
        "method": "How this briefing was assembled",
        "queries": "Queries used",
        "criteria": "Inclusion and exclusion criteria",
        "include": "include",
        "exclude": "exclude",
        "cards": "Paper by paper",
        "comparison": "Comparison",
        "gaps": "Gaps and open questions",
        "further_reading": "Suggested next reading",
        "references": "References",
        "appendix": "Appendix: generation parameters",
        "problem": "Problem",
        "method_field": "Method",
        "data_field": "Data and experiments",
        "findings": "Key findings",
        "limitations": "Limitations",
        "relevance": "Relevance to the topic",
        "ideas": "Reusable ideas",
        "confidence": "Confidence",
        "col_reference": "Ref",
        "col_task": "Task",
        "col_method": "Method family",
        "col_data": "Data",
        "col_metrics": "Metrics",
        "col_result": "Main result",
        "col_paper": "Paper",
        "col_finding": "Headline finding",
        "col_relevance": "Why it matters",
        "run_id": "Run id",
        "generated_at": "Generated at",
        "model": "Model",
        "paper_count": "Papers briefed",
        "prompt_versions": "Prompt versions",
        "llm_calls": "Model calls",
        "tokens": "Tokens used",
    },
    "zh": {
        "title_suffix": "文献简报",
        "subtitle": "由多智能体流水线自动生成",
        "toc": "目录",
        "summary": "一句话结论",
        "overview": "主题速览",
        "overview_caption": "本简报所依据的论文，以及它们与主题的关系。",
        "overview_table": "速览表",
        "background": "主题背景",
        "method": "检索方法与纳入排除标准",
        "queries": "检索式",
        "criteria": "纳入与排除标准",
        "include": "纳入",
        "exclude": "排除",
        "cards": "逐篇论文",
        "comparison": "横向对比",
        "gaps": "研究空白与开放问题",
        "further_reading": "后续阅读建议",
        "references": "参考文献",
        "appendix": "附录：生成参数",
        "problem": "问题",
        "method_field": "方法",
        "data_field": "数据与实验",
        "findings": "主要结论",
        "limitations": "局限",
        "relevance": "与主题的关系",
        "ideas": "可复用点",
        "confidence": "置信度",
        "col_reference": "引用",
        "col_task": "任务",
        "col_method": "方法族",
        "col_data": "数据",
        "col_metrics": "指标",
        "col_result": "主要结果",
        "col_paper": "论文",
        "col_finding": "主要发现",
        "col_relevance": "与主题的关系",
        "run_id": "运行编号",
        "generated_at": "生成时间",
        "model": "模型",
        "paper_count": "论文数量",
        "prompt_versions": "Prompt 版本",
        "llm_calls": "模型调用次数",
        "tokens": "Token 用量",
    },
}


@dataclass(frozen=True)
class ReportContext:
    """Everything the template needs, gathered by the orchestrator (Step 13)."""

    briefing: Briefing
    selected: SelectedPapers
    search_plan: SearchPlan | None = None
    model_id: str = "unknown"
    prompt_versions: dict[str, str] = field(default_factory=dict)
    llm_calls: int = 0
    total_tokens: int = 0
    generated_at: datetime | None = None


@dataclass(frozen=True)
class PdfCheck:
    """What was verified about a produced PDF."""

    ok: bool
    page_count: int
    text_extractable: bool
    fonts_embedded: bool
    cjk_present: bool
    problem: str = ""


@dataclass(frozen=True)
class RenderResult:
    """Auditable outcome of a render, surfaced in ``manifest.json``."""

    pdf_path: Path
    html_path: Path
    renderer: str
    fallback: bool
    page_count: int
    fonts_embedded: bool


class PdfEngine(Protocol):
    name: str

    def render(self, html: str, target: Path, *, html_path: Path) -> None: ...


def _prepare_library_path() -> None:
    """Point dyld at Homebrew's libraries before WeasyPrint is imported."""
    if sys.platform != "darwin":
        return
    if Path(HOMEBREW_LIB).is_dir():
        os.environ.setdefault("DYLD_FALLBACK_LIBRARY_PATH", HOMEBREW_LIB)


def _load_weasyprint() -> Any:
    """Import WeasyPrint only after the library path has been repaired."""
    _prepare_library_path()
    from weasyprint import HTML

    return HTML


class WeasyPrintEngine:
    """Primary engine: full paged-media support, runs in-process."""

    name = "weasyprint"

    def render(self, html: str, target: Path, *, html_path: Path) -> None:
        document = _load_weasyprint()(string=html, base_url=str(html_path.parent))
        document.write_pdf(str(target))


class ChromiumEngine:
    """Fallback engine: headless Chrome printing the same HTML file."""

    name = "chromium"

    def __init__(self, binary: Path | None = None) -> None:
        self._binary = binary

    @property
    def binary(self) -> Path | None:
        if self._binary is not None:
            return self._binary
        for candidate in CHROME_CANDIDATES:
            if Path(candidate).is_file():
                return Path(candidate)
        return None

    def render(self, html: str, target: Path, *, html_path: Path) -> None:
        binary = self.binary
        if binary is None:
            raise RenderError("no chromium binary found for the fallback renderer")
        # A fixed argv list, no shell, no user-controlled command.
        completed = subprocess.run(
            [
                str(binary),
                "--headless",
                "--disable-gpu",
                "--no-sandbox",
                f"--print-to-pdf={target}",
                html_path.as_uri(),
            ],
            capture_output=True,
            check=False,
        )
        if completed.returncode != 0 or not target.is_file():
            detail = completed.stderr.decode("utf-8", "replace")[-300:]
            raise RenderError(f"chromium exited with {completed.returncode}: {detail}")


def default_engines() -> list[PdfEngine]:
    return [WeasyPrintEngine(), ChromiumEngine()]


def render_report(
    context: ReportContext,
    out_dir: Path,
    *,
    engines: Sequence[PdfEngine] | None = None,
) -> RenderResult:
    """Render the briefing, falling back through the engine list in order."""
    out_dir.mkdir(parents=True, exist_ok=True)
    stage_dir = out_dir / "_stages"
    stage_dir.mkdir(parents=True, exist_ok=True)

    html = render_html(context)
    html_path = stage_dir / STAGE_HTML_PATH
    html_path.write_text(html, encoding="utf-8")
    pdf_path = out_dir / "report.pdf"

    failures: list[str] = []
    for position, engine in enumerate(engines or default_engines()):
        try:
            engine.render(html, pdf_path, html_path=html_path)
        except Exception as exc:
            failures.append(f"{engine.name}: {exc}")
            logger.warning(
                "pdf engine failed",
                extra={"engine": engine.name, "reason": str(exc)},
            )
            continue

        check = verify_pdf(pdf_path, expect_cjk=context.briefing.lang == "zh")
        if not check.ok:
            failures.append(f"{engine.name}: {check.problem}")
            logger.warning(
                "pdf failed verification",
                extra={"engine": engine.name, "reason": check.problem},
            )
            continue

        return RenderResult(
            pdf_path=pdf_path,
            html_path=html_path,
            renderer=engine.name,
            fallback=position > 0,
            page_count=check.page_count,
            fonts_embedded=check.fonts_embedded,
        )

    raise RenderError("no pdf engine produced a usable report: " + "; ".join(failures))


# --- html ---------------------------------------------------------------------


def render_html(context: ReportContext) -> str:
    briefing = context.briefing
    labels = LABELS[briefing.lang]
    mapping = build_reference_map(context.selected)
    references = build_references(context.selected)
    generated_at = context.generated_at or datetime.now(UTC)

    cards: list[dict[str, Any]] = []
    for position, (card, screened) in enumerate(
        zip(briefing.paper_cards, context.selected.items, strict=True),
        start=1,
    ):
        paper = screened.paper
        cards.append(
            {
                "number": mapping.get(card.citation_key, position),
                "title": paper.title,
                "authors": format_authors(paper.authors),
                "venue": paper.venue or paper.origin,
                "year": paper.year if paper.year is not None else "n.d.",
                "year_value": paper.year,
                "url": paper.url,
                "problem": card.analysis.problem,
                "method": card.analysis.method,
                "data_and_experiments": card.analysis.data_and_experiments,
                "key_findings": card.analysis.key_findings,
                "limitations": card.analysis.limitations,
                "relevance": card.analysis.relevance,
                "reusable_ideas": card.analysis.reusable_ideas,
                "confidence": card.analysis.confidence,
            }
        )

    comparison: list[dict[str, Any]] = [
        {
            "number": mapping.get(row.citation_key, position),
            "task": row.task,
            "method_family": row.method_family,
            "data": row.data,
            "metrics": row.metrics,
            "main_result": row.main_result,
        }
        for position, row in enumerate(briefing.comparison, start=1)
    ]

    family_by_number = {row["number"]: row["method_family"] for row in comparison}
    summary_rows = [
        {
            "number": card["number"],
            "title": truncate(card["title"], 58),
            "year": card["year"],
            "method_family": truncate(family_by_number.get(card["number"], "—"), 26),
            "finding": truncate(card["key_findings"][0], 130),
            "relevance": truncate(card["relevance"], 190),
        }
        for card in cards
    ]
    topic_overview = render_topic_overview(
        briefing.topic,
        [
            OverviewEntry(
                number=card["number"],
                title=card["title"],
                year=card["year_value"],
                method_family=family_by_number.get(card["number"], ""),
            )
            for card in cards
        ],
    )

    def claims(items: Sequence[Claim]) -> list[dict[str, str]]:
        return [
            {
                "text": claim.text,
                "citations": resolve_claim_keys(claim.citation_keys, mapping),
            }
            for claim in items
        ]

    sections = _sections(labels, has_further_reading=bool(briefing.further_reading))
    plan = context.search_plan

    environment = Environment(
        loader=FileSystemLoader(str(TEMPLATE_DIR)),
        autoescape=select_autoescape(("html", "xml")),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    template = environment.get_template(TEMPLATE_NAME)
    return template.render(
        lang=briefing.lang,
        labels=labels,
        title=f"{briefing.topic} — {labels['title_suffix']}",
        subtitle=labels["subtitle"],
        run_id=briefing.run_id,
        model_id=context.model_id,
        prompt_versions=context.prompt_versions,
        llm_calls=context.llm_calls,
        total_tokens=context.total_tokens,
        generated_at=generated_at.strftime("%Y-%m-%d %H:%M UTC"),
        styles=STYLESHEET.read_text(encoding="utf-8"),
        sections=sections,
        executive_summary=resolve_citations(briefing.executive_summary, mapping),
        background_html=render_markdown(resolve_citations(briefing.background_md, mapping)),
        method_html=render_markdown(resolve_citations(briefing.method_md, mapping)),
        queries=[f"{query.source}: {query.q}" for query in (plan.queries if plan else [])],
        inclusion_criteria=list(plan.inclusion_criteria) if plan else [],
        exclusion_criteria=list(plan.exclusion_criteria) if plan else [],
        cards=cards,
        summary_rows=summary_rows,
        topic_overview=topic_overview,
        comparison=comparison,
        gaps=claims(list(briefing.gaps_and_open_questions)),
        further_reading=claims(list(briefing.further_reading)),
        references=references,
    )


def _sections(labels: dict[str, str], *, has_further_reading: bool) -> list[dict[str, str]]:
    """The fixed chapter list of AGENTS.md §8, in order."""
    sections = [
        {"anchor": "summary", "title": labels["summary"]},
        {"anchor": "overview", "title": labels["overview"]},
        {"anchor": "background", "title": labels["background"]},
        {"anchor": "method", "title": labels["method"]},
        {"anchor": "cards", "title": labels["cards"]},
        {"anchor": "comparison", "title": labels["comparison"]},
        {"anchor": "gaps", "title": labels["gaps"]},
    ]
    if has_further_reading:
        sections.append({"anchor": "further-reading", "title": labels["further_reading"]})
    sections.append({"anchor": "references", "title": labels["references"]})
    sections.append({"anchor": "appendix", "title": labels["appendix"]})
    return sections


# --- pdf verification ---------------------------------------------------------


def verify_pdf(path: Path, *, expect_cjk: bool) -> PdfCheck:
    """Prove the PDF is usable: pages, extractable text, embedded fonts."""
    if not path.is_file() or path.stat().st_size == 0:
        return PdfCheck(False, 0, False, False, False, "the pdf file is empty")

    try:
        reader = PdfReader(str(path))
        page_count = len(reader.pages)
        text = "\n".join(page.extract_text() or "" for page in reader.pages)
        fonts_embedded = _all_fonts_embedded(reader)
    except Exception as exc:
        return PdfCheck(False, 0, False, False, False, f"unreadable pdf: {exc}")

    text_extractable = bool(text.strip())
    cjk_present = contains_cjk(text)

    problem = ""
    if page_count == 0:
        problem = "the pdf has no pages"
    elif not text_extractable:
        problem = "no text could be extracted (rendered as an image?)"
    elif not fonts_embedded:
        problem = "the pdf contains fonts that are not embedded"
    elif expect_cjk and not cjk_present:
        problem = "a Chinese briefing produced no extractable Chinese text"

    return PdfCheck(
        ok=not problem,
        page_count=page_count,
        text_extractable=text_extractable,
        fonts_embedded=fonts_embedded,
        cjk_present=cjk_present,
        problem=problem,
    )


def _all_fonts_embedded(reader: PdfReader) -> bool:
    seen = 0
    embedded = 0
    for page in reader.pages:
        resources = page.get("/Resources") or {}
        fonts = resources.get("/Font") or {}
        for reference in fonts.values():
            font = reference.get_object()
            seen += 1
            if _font_is_embedded(font):
                embedded += 1
    return seen > 0 and seen == embedded


def _font_is_embedded(font: Any) -> bool:
    descriptor = font.get("/FontDescriptor")
    if descriptor is None:
        for descendant in font.get("/DescendantFonts") or []:
            candidate = descendant.get_object().get("/FontDescriptor")
            if candidate is not None:
                descriptor = candidate
                break
    if descriptor is None:
        return False
    return any(key in descriptor for key in ("/FontFile", "/FontFile2", "/FontFile3"))


def chromium_available() -> bool:
    """Whether a fallback engine is installed at all."""
    return ChromiumEngine().binary is not None or shutil.which("chromium") is not None
